// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import { user } from "@heroui/theme";
import { User } from "lucide-react";

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type CourseCategory = {
  category: string;
  weight: number;
  criterions: {
    id: number;
    name: string;
  }[];
};


export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type PlatformRole = {
  id: number;
  name: string;
  scope: string;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  active: boolean;
  status: string;
  platformRoles: PlatformRole[];
  platformPermissions: string[];
}>;

export type AuthResponse = {
  message: string;
};

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
  public: boolean;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

export type EventMembership = Entity<{
  eventId: number;
  userId: number;
  eventRole: "Participant" | "Juror";
  event: Event;
}>;

export type role = Entity<{
  description?: string;
  id: number;
  name: "Juror" | "Participant";
  scope: string;
}>;

export type Event = Entity<{
  id: number;
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  inscriptionDeadline: string;
  accessCode: string;
  isPubliclyJoinable: boolean;
  evaluationsOpened: boolean;
  statusName: string;
  location?: string;
  locationDetail?: string;
  eventType: "Competition" | "Exhibition";
  inscriptionRequirements?: string;
  cost?: number;
  minimumTeamSize?: number;
  specificInscriptionDetails?: { title: string; description: string }[];
  aboutOurAllies?: string;
  organizations?: string[];
  collaborators?: string[];
  awards?: { top: number; category: string; description: string; prizeMoney?: number }[];
  status?: number;
  active: boolean;
  role: role;
  createdAt: number;
  updatedAt: number;
}>;

export type Project = Entity<{
  id: number;
  eventId: number;
  courseId: number;
  name: string;
  description?: string;
  eventNumber?: string;
  state: "UNDER_REVIEW" | "APPROVED" | "REJECTED";
  participants: ProjectParticipant[];
  documents: ProjectDocument[];
  jurorAssignments: ProjectAssignment[];
  pendingParticipants: ProjectParticipant[];
  evaluated: boolean;
  createdAt: number;
  updatedAt: number;
}>;

export type ProjectDocument = Entity<{
  id: string;
  projectId: string;
  type: string;
  url: string;
  createdAt: number;
  project: Project;
}>;

export type ProjectParticipant = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  projectId: string;
  ParticipantCode?: string;
  project: Project;
}>;

export type ProjectAssignment = Entity<{
  projectId: string;
  memberEventId: string;
  assigneAt: Date;
  updatedAt: Date;
  project: Project;
}>;

export type Course = Entity<{
  id: number;
  eventId: number;
  code: string;
  description?: string;
  active: boolean;
  event?: { id: number; name: string };
  createdAt: number;
}>;

export type EvaluationScoreInput = {
  criterion: string;
  score: number;
};

export type Evaluation = Entity<{
  memberUserId: string;
  evaluatorId: string;
  grade: number;
  comments: string;
  scores: EvaluationScoreInput[];
}>;

export type Jury = Entity<{
  email: string;
  eventIds: number[];
  projectIds: number[];
  invitationStatus: "pending" | "accepted" | "declined";
}>;

// Real API types for invitations
// Status values: 0 = PENDING, 1 = ACCEPTED, 2 = DECLINED, 3 = EXPIRED
export type InvitationStatus = 0 | 1 | 2 | 3;

export type InvitationRole = {
  id: number;
  name: string;
  description: string;
  scope: string;
};

export type JuryInvitation = {
  id: string;
  token: string;
  email: string;
  targetType: string;
  targetId: number;
  status: InvitationStatus;
  expiresAt: string;
  invitedByUserId: number;
  invitedUserId: number | null;
  roleIds: number[];
  createdAt: string;
  roles: InvitationRole[];
  event: Event;
  project: any | null;
};

export type InvitationsMeta = {
  total: number;
  itemsOnCurrentPage: number;
  itemsPerPage: number;
  currentPage: number;
  totalPages: number;
};

export type Administrator = Entity<{
  email: string;
  invitationStatus: "pending" | "accepted" | "declined";
}>;

export type Criterion = Entity<{
  id: number;
  eventId: number;
  name: string;
  description: string;
  weight: number;
  active: boolean;
  courseIds: number[];
  createdAt?: number;
}>;

export type CriterionCourse = Entity<{
  courseId: number;
  criterionId: number;
}>;
